### ISSUE TITLE
Option for coverage or counts

### ISSUE THREAD

**Issue by TYMichaelsen** [wwood/dirseq#2]
Hi Ben,
Would it be possible to have a command line option specifying whether to output as coverage or number of reads? Currently it's outputting average coverage, but that is not what i want for downstream analysis. 

Thanks for a nice, simple program!

Best Thomas

**Comment by wwood** [comment]
Hi,
Sure, in fact it already does with `--measure-type count`. This wasn't clear from the README so I've updated it.

Thanks for the kind words. Let me know if there is anything else.
ben

**Comment by TYMichaelsen** [comment]
Awesome, thanks!

**Comment by TYMichaelsen** [comment]
Hi again Ben,

While you're at it, could you also take a look at the --accepted-feature-types argument? It looks like the argument is set as default CDS by the program, it throws and error when i try to set it myself.

Best,
Thomas

**Comment by wwood** [comment]
Ah, right that option wasn't working. I fixed it just now in the master branch, would you mind testing it? If you are happy I'll release 0.2.1.

If you've already got dirseq installed then I think it should just be a simple matter of running bin/dirseq from the git checkout.

Thanks for the bug report.

ben

**Comment by TYMichaelsen** [comment]
Great, it works for me now :) 

Thanks again

**Comment by wwood** [comment]
Alrighty, 0.2.1 now pushed.
