### ISSUE TITLE
Associate sequence ID with output

### ISSUE THREAD

**Issue by TYMichaelsen** [wwood/dirseq#3]
hi Ben,

I am using your dirseq script, which really works nicely. But, I would like to be able to merge the output with other files I've generated using a identity that links directly to the ORF/gene sequence that is mapped. ATM I only have indirect ways of doing so, like the contig, position and strand. 

To be specific, I am working with output from Prokka, meaning the 9th column in the .gff file has a ID and/or locus_tag with a unique ORF identity. If this could be included in the output as a column somehow I would be very happy!

Hope my question is clear. 

Best, 
Thomas

**Comment by wwood** [comment]
Hi Thomas,

I've defaulted it to "ID", but you can modify it yourself from there. Implemented in 41cda02. If you like it I'll bump the release - let me know.
ta

**Comment by TYMichaelsen** [comment]
Hi Ben, 
Works like a charm, I like that feature!

**Comment by wwood** [comment]
Cheers.
