### ISSUE TITLE
Running dirseq

### ISSUE THREAD

**Issue by dominikmerges** [wwood/dirseq#5]
Dear Ben,

I would like to give dirseq a try. However, I am unsure how to actually start the script.
So far, I downloaded the folder and tried in bash command line: ruby dirseq
It would great if you could give me a hint.

Many thanks and all the best,
Dominik

**Comment by wwood** [comment]
Hi,

I'm not sure you've installed it correctly either. I've updated the README with clearer install and added an example running invocation.

HTH, let me know otherwise.
Thanks, ben

**Comment by dominikmerges** [comment]
Hi Ben,
many thanks! It works like a charm. Only think I had to do is to update to another version of ruby, since gem is brocken in the standard conda ruby version. This one works for me:
conda install -c conda-forge ruby=2.4.5=h48a8d5d_1003
source: https://github.com/ContinuumIO/anaconda-issues/issues/9863#issuecomment-524183296

All the best,
Dominik

**Comment by wwood** [comment]
Excellent, thank you - that link of yours helped me too.
